In [1]:
import pandas as pd 
from sklearn.feature_extraction import DictVectorizer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
train_data = pd.read_csv('C:/Users/18280/Desktop/RS/主课/assignment/train.csv')
test_data = pd.read_csv('C:/Users/18280/Desktop/RS/主课/assignment/test.csv')

In [3]:
train_data.head()

,user_id,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1374,58,No,Travel_Rarely,605,Sales,21,3,Life Sciences,1,...,3,80,1,29,2,2,1,0,0,0
1,1092,45,No,Travel_Rarely,950,Research & Development,28,3,Technical Degree,1,...,4,80,1,8,3,3,5,4,0,3
2,768,40,No,Travel_Rarely,300,Sales,26,3,Marketing,1,...,2,80,1,8,3,2,7,7,7,5
3,569,36,No,Non-Travel,1434,Sales,8,4,Life Sciences,1,...,2,80,0,10,1,3,10,7,0,9
4,911,25,Yes,Travel_Frequently,599,Sales,24,1,Life Sciences,1,...,4,80,0,1,4,3,1,0,1,0

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 36 columns):
user_id                     1176 non-null int64
Age                         1176 non-null int64
Attrition                   1176 non-null object
BusinessTravel              1176 non-null object
DailyRate                   1176 non-null int64
Department                  1176 non-null object
DistanceFromHome            1176 non-null int64
Education                   1176 non-null int64
EducationField              1176 non-null object
EmployeeCount               1176 non-null int64
EmployeeNumber              1176 non-null int64
EnvironmentSatisfaction     1176 non-null int64
Gender                      1176 non-null object
HourlyRate                  1176 non-null int64
JobInvolvement              1176 non-null int64
JobLevel                    1176 non-null int64
JobRole                     1176 non-null object
JobSatisfaction             1176 non-null int64
MaritalStatus               1176 non-null object
MonthlyIncome               1176 non-null int64
MonthlyRate                 1176 non-null int64
NumCompaniesWorked          1176 non-null int64
Over18                      1176 non-null object
OverTime                    1176 non-null object
PercentSalaryHike           1176 non-null int64
PerformanceRating           1176 non-null int64
RelationshipSatisfaction    1176 non-null int64
StandardHours               1176 non-null int64
StockOptionLevel            1176 non-null int64
TotalWorkingYears           1176 non-null int64
TrainingTimesLastYear       1176 non-null int64
WorkLifeBalance             1176 non-null int64
YearsAtCompany              1176 non-null int64
YearsInCurrentRole          1176 non-null int64
YearsSinceLastPromotion     1176 non-null int64
YearsWithCurrManager        1176 non-null int64
dtypes: int64(27), object(9)
memory usage: 330.8+ KB

In [5]:
#数据集拆分
train_x,validation_x,train_y,validation_y = train_test_split(train_data,
                                                             train_data.Attrition,
                                                             test_size=0.25,
                                                             random_state=33)
# 特征选择
train_features = train_x[train_x.columns.difference(['user_id','Attrition'])]
train_labels = train_x['Attrition']
validation_features = validation_x[validation_x.columns.difference(['user_id','Attrition'])]
validation_labels = validation_x['Attrition']
test_features = test_data[test_data.columns.difference(['user_id','Attrition'])]
# print(validation_features.head())
# print('_'*30)
# print(train_features.head())
# print('-'*30)
# print(train_labels.head())
# print('-'*30)t
print(validation_labels.head())
# print(train_features.to_dict(orient='records')[1])
# print(validation_labels.to_dict(orient='records'))

520      No
1002     No
1032     No
1110    Yes
260      No
Name: Attrition, dtype: object

In [6]:
# 将非数字化数据数值化
dvec = DictVectorizer(sparse=True)
train_features = dvec.fit_transform(train_features.to_dict(orient='records'))
# train_labels =dvec.transform(train_labels.to_dict(orient='records'))
# train_labels =dvec.transform(train_labels.to_dict())
validation_features = dvec.transform(validation_features.to_dict(orient='records'))
# validation_labels = dvec.transform(validation_labels.to_dict(orient='records'))
# validation_labels = dvec.transform(validation_labels.to_dict())
test_features = dvec.transform(test_features.to_dict(orient='records'))

In [7]:
# 采用Z-score规范化
ss = preprocessing.StandardScaler(with_mean=False)
train_features = ss.fit_transform(train_features)
validation_features = ss.transform(validation_features)
test_features = ss.transform(test_features)

In [10]:
lr = LogisticRegression()
lr.fit(train_features,train_labels)

C:\Users\18280\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
pre_labels = lr.predict(validation_features)
acc_lr = round(accuracy_score(validation_labels,pre_labels),6)
print('准确率：%.4lf'%acc_lr)

准确率：0.8878